name: Build and Package for macOS

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-macos:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: 21
        distribution: 'zulu'

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 22.14.0

    - name: Install Maven 3.9.9
      run: |
        curl -O https://archive.apache.org/dist/maven/maven-3/3.9.9/binaries/apache-maven-3.9.9-bin.tar.gz
        sudo tar xzvf apache-maven-3.9.9-bin.tar.gz -C /usr/local/
        echo "/usr/local/apache-maven-3.9.9/bin" >> $GITHUB_PATH
        rm apache-maven-3.9.9-bin.tar.gz

    - name: Build mygit CLI
      run: |
        cd mygitImplementation
        cmake -S . -B build -DCMAKE_BUILD_TYPE=Release
        cmake --build build

    - name: Build Spring Boot backend
      run: |
        cd backend
        mvn clean package -DskipTests

    - name: Build React frontend
      run: |
        cd frontend
        npm install
        npm run build

    - name: Create distribution package
      run: |
        mkdir -p dist/{backend,bin/macos,frontend/build}
        cp backend/target/backend-*.jar dist/backend/
        cp mygitImplementation/build/src/mygit dist/bin/macos/
        chmod +x dist/bin/macos/mygit
        cp -r frontend/build/* dist/frontend/build/
        cp launch.sh dist/
        chmod +x dist/launch.sh
        xattr -d com.apple.quarantine dist/bin/macos/mygit

    - name: Package artifacts
      run: |
        cd dist
        zip -r Git-from-scratch-cpp-macos.zip .

    - uses: actions/upload-artifact@v4
      with:
        name: Git-from-scratch-cpp-macos
        path: dist/Git-from-scratch-cpp-macos.zip